Jfshaw1/feature/confirm delete menu
CMPUT301F23T01/Sigma-Blue pull request #184
Opened 2023-11-29 00:15 UTC by JoshuaShaw-13

Added confirm deletion menus for deleting items in list view and detail view and also for deleting tags. Let me know if there are other places we delete things that require the menu.

Problem with tags: 
 - When selecting tags there is no indication that they are selected in UI.
 - When delete is pressed, tags that were selected go away but come back after fragment is reloaded

Note: these problems were present before I had made my changes, I am not sure if they are known problems

2023-11-29 00:21 UTC, lizard-52 commented
At least the first of those problems is know an is fixed (?) in Ben's new UI branch. Not sure about the other.

2023-11-29 21:43 UTC, lizard-52 commented
Second issue is fixed in my tag colour PR

2023-12-01 00:52 UTC, JoshuaShaw-13 commented
Previous issues seem to be resolved now, but app crashes when adding a new tag and when deleting multiple tags (but not when deleting a single tag). After restarting the app when it crashes from adding a tag the tag is actually created and appears in the tag manager. But after restarting from a crash because of deleting multiple tags the tags are not deleted.

2023-12-01 01:03 UTC, lizard-52 commented
I'm not worried about those bugs, we're doing an overhaul of the tag manager anyways (in ben's UI PR).

2023-12-01 01:12 UTC, JoshuaShaw-13 commented
Sounds good, then I think this PR is good to review

2023-12-01 02:36 UTC, waridh approved these changes
Cool, it works. Thank you.

2023-12-01 02:40 UTC, lizard-52 requested changes
Please factor the menu out into a method somewhere. We will need it in more places

2023-12-01 18:21 UTC, waridh commented on code/app/src/main/java/com/example/sigma_blue/activities/ViewListActivity.java
> +        viewHolder.deleteSelectedButton.setOnClickListener(v -> {
If its going to be reused, Nikolai is right. I don't know this side of the application, so I am not sure how much reuse we are planning out of it.

2023-12-02 03:34 UTC, JoshuaShaw-13 commented
Method has been made into an interface. I don't know if this is the best way to implement it but I wanted to make the change to get feedback if any (that's why its in placeholder). I can change it up tomorrow if needed, but wanted to get this out before stopping for the day

2023-12-02 04:23 UTC, merged